### ISSUE TITLE
Comentar el codi

### ISSUE THREAD

**Issue by BrunoBA91** [Masclins/ensignepedia#36]
Cal comentar tot el codi que anem fent per a tenir clar en tot moment i en el futur què és el que fa.

**Comment by Masclins** [comment]
#37 soluciona aquesta Issue.
@BrunoBA91 recorda que posant `resolves #36` en el cos de la pull-request ara s'hauria tancat aquesta Issue automàticament.

**Comment by BrunoBA91** [comment]
Aaah és veritat. Intentaré recordar ara lo del "resolves". Perfecte doncs ;)
